version = FBB7.0.11
callsign = OE9FBB.OE.EU
ssid = 1
qraloc = JN77RB
city = Interop
name = Interop
sysop = OE1TST
data = /var/ax25/fbb
config = /etc/ax25/fbb
messages = /var/ax25/fbb/mail
compressed = /var/ax25/fbb/binmail
fbbdos = *,*,/var/ax25/fbb/fbbdos,*,*,*,*,*
yapp = /var/ax25/fbb/fbbdos/yapp
docs = /var/ax25/fbb/docs
pg = /usr/lib/fbb/pg
fdir = /usr/lib/fbb/filter
sdir = /usr/lib/fbb/server
tdir = /usr/lib/fbb/tool
import = /var/ax25/fbb/mail/mail.in
logs = OK
test = NO
fbbfwd = OK 160
fbbcomp = OK 3
askinfo = NO
mask = 3616
security = 0 4 59
warning = 255
housekeeping = 2
timeout = 10 20
maxdownload = 0 0
localtime = 0
beacon = 0
scroll = 1500 1500 1500
fwdheader = [$c] $$:$R
maxbids = 30000
lifetime = 30
zipcode = 00000
