#!/usr/bin/env bun
/**
 * Generate `assets.generated.ts` — the embed manifest the single-binary build uses. Walks the built
 * SPA (`apps/web/dist`) and `db/migrations`, emitting `import … with { type: "file" }` statements so
 * `bun build --compile` embeds every file into the executable. Run by build-exe.sh before compiling.
 * The output is gitignored; in dev the launcher falls back to reading these dirs from disk.
 */
import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, basename, sep } from "node:path";

const HERE = import.meta.dir;                 // deploy/desktop
const ROOT = join(HERE, "..", "..");
const DIST = join(ROOT, "apps", "web", "dist");
const MIG = join(ROOT, "db", "migrations");

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}
const rel = (f: string) => "./" + relative(HERE, f).split(sep).join("/");
const url = (f: string) => "/" + relative(DIST, f).split(sep).join("/");

const spa = walk(DIST);
const migs = readdirSync(MIG).filter((f) => f.endsWith(".sql")).sort().map((f) => join(MIG, f));

let imports = "";
let spaMap = "";
let migArr = "";
spa.forEach((f, i) => {
  imports += `import s${i} from ${JSON.stringify(rel(f))} with { type: "file" };\n`;
  spaMap += `  ${JSON.stringify(url(f))}: s${i},\n`;
});
migs.forEach((f, i) => {
  imports += `import m${i} from ${JSON.stringify(rel(f))} with { type: "file" };\n`;
  migArr += `  { name: ${JSON.stringify(basename(f))}, file: m${i} },\n`;
});

const out =
  `// AUTO-GENERATED by gen-assets.ts — do not edit (gitignored). Embeds the SPA + migrations.\n` +
  imports +
  `\nexport const SPA: Record<string, string> = {\n${spaMap}};\n` +
  `\nexport const MIGRATIONS: { name: string; file: string }[] = [\n${migArr}];\n`;

writeFileSync(join(HERE, "assets.generated.ts"), out);
console.log(`>> embedded ${spa.length} SPA files + ${migs.length} migrations -> assets.generated.ts`);
