// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * The layouts of the two example environment files, rendered by generate.mjs: a string is a line written
 * as is (a comment or a blank line), an object is a setting — `off` writes it as a commented template
 * line, and a missing `value` takes the schema's default. Every key must be in the schema, and a secret
 * carries no value here except a `placeholder` (the APRS-IS passcode's `00000` / `-1`), which setup.sh
 * reads as unset.
 */
export const ENV_FILES = [
  {
    path: ".env.example",
    lines: [
      "# --- ingest box ---",
      { key: "APRSIS_HOST", value: "rotate.aprs2.net" },
      { key: "APRSIS_PORT", value: "14580" },
      { key: "APRSIS_CALLSIGN", value: "N0CALL" },
      "# -1 = receive-only (no transmit)",
      { key: "APRSIS_PASSCODE", value: "-1", placeholder: true },
      "# OE example: ~Graz, 300km",
      { key: "APRSIS_FILTER", value: "r/47.07/15.42/300" },
      { key: "INGEST_URL", value: "http://127.0.0.1:8787/ingest" },
      "# REQUIRED — the same value the gateway has. Generate one: openssl rand -hex 24 (the gateway refuses the",
      "# change-me default). It is the only gateway secret this box holds: never put OPERATOR_SECRET or",
      "# SESSION_SECRET here.",
      { key: "INGEST_SECRET", value: "" },
      { key: "BATCH_MS", value: "1500" },
      "",
      "# --- APRS-IS uplink: answers to radio commands, BBS mail by APRS, announced finds, weather ---",
      "# Blank: a box whose APRSIS_CALLSIGN shares the gateway's service-call base call logs in as the",
      "# service call with APRSIS_PASSCODE. Set both to log in as another call of that base call.",
      { key: "APRSIS_SERVICE_CALL", value: "" },
      { key: "APRSIS_SERVICE_PASS", value: "" },
      "",
      "# --- optional: extra transports (each forwards to /ingest with its own port) ---",
      "# KISS-over-TCP TNC (e.g. Direwolf): set host to enable.",
      { key: "KISS_TNC_HOST", value: "" },
      { key: "KISS_TNC_PORT", value: "8001" },
      "# RF digipeater (needs a KISS TNC). Set DIGI_CALL to your station call to enable n-N repeating.",
      { key: "DIGI_CALL", value: "" },
      { key: "DIGI_ALIASES", value: "WIDE1,WIDE2" },
      "# Bidirectional APRS IGate (needs a KISS TNC + a real callsign & APRS-IS passcode for TX).",
      { key: "IGATE_CALL", value: "" },
      { key: "IGATE_PASS", value: "" },
      "# APRS-IS filter for the IS->RF (message) direction",
      { key: "IGATE_FILTER", value: "t/m" },
      '# seconds a station counts as "heard locally" for TX-gating',
      { key: "IGATE_LOCAL_TTL", value: "1800" },
      "# RF path of messages gated IS->RF, comma-separated (blank = direct; e.g. WIDE1-1 to reach one hop out)",
      { key: "IGATE_TX_PATH", value: "" },
      "# IS->RF pacing: messages gated at once, then one more every N seconds (ceiling: 10 at once, 6 s)",
      { key: "IGATE_TX_BURST", value: "6" },
      { key: "IGATE_TX_REFILL_SEC", value: "10" },
      "# Callsign naming this box as the receiving site of frames its KISS / AGWPE / host-mode TNC hears",
      "# directly (default: IGATE_CALL). List it in the gateway's FIRST_PARTY_SITES so those frames count toward",
      "# Tier A. Only for a TNC you operate: leave it blank when the TNC host is someone else's station.",
      { key: "RF_SITE_CALL", value: "" },
      "# Meshtastic — licensed nodes only (licensed/ham mode on, callsign as long name). Either the node's TCP",
      "# API (a WiFi/Ethernet node, port 4403) or a broker's protobuf feed, e.g. mqtt://user:pass@broker.",
      { key: "MESHTASTIC_HOST", value: "" },
      { key: "MESHTASTIC_PORT", value: "4403" },
      { key: "MESHTASTIC_MQTT_URL", value: "" },
      { key: "MESHTASTIC_MQTT_TOPIC", value: "msh/#" },
      "# MeshCom (LoRa ham mesh) via the nodes' ExtUDP interface (on the node: --extudpip <this box> + --extudp on).",
      "# MESHCOM_NODE lists the allowed node address(es), each optionally =CALL, e.g. 192.168.1.50=OE8APR-12.",
      "# The node's call marks its own frames and, for a direct LoRa hearing, names it as the receiving site",
      "# (attest it at the gateway with FIRST_PARTY_SITES).",
      { key: "MESHCOM_NODE", value: "" },
      { key: "MESHCOM_PORT", value: "1799" },
      "# Blank = this host's address on the node's subnet. Never 0.0.0.0 on a host reachable from the internet.",
      { key: "MESHCOM_BIND", value: "" },
      "# Other local tools that also want the raw datagrams, e.g. 127.0.0.1:1800 (only one process can own 1799).",
      { key: "MESHCOM_FANOUT", value: "" },
      "# Max datagrams per second per node, and minutes of silence before a warning.",
      { key: "MESHCOM_RATE", value: "20" },
      { key: "MESHCOM_STALE_MIN", value: "30" },
      '# "1" lets the box answer radio commands (FOUND / DNF / NOTE / HELP) through its MeshCom nodes. Needs',
      "# BOX_ID and BOX_TX=1. The node transmits under its own call, which must match MESHCOM_TX_CALL",
      "# (blank = BOX_CALL, then IGATE_CALL, DIGI_CALL).",
      { key: "MESHCOM_TX", value: "" },
      { key: "MESHCOM_TX_CALL", value: "" },
      "# Send pacing: sends at once, then one more every N seconds (ceiling: 10 at once, 6 s)",
      { key: "MESHCOM_TX_BURST", value: "3" },
      { key: "MESHCOM_TX_REFILL_SEC", value: "60" },
      "",
      "# --- optional: remote control from the web app (Shack -> Remote control) ---",
      "# The box polls the gateway for commands you queue in the app; no inbound port is opened.",
      "# BOX_ID is the id you enter in the app. At start the box prints a one-time pairing code; enter it in the",
      "# app to link the box to your account. Status and switching functions off work with BOX_ID alone.",
      { key: "BOX_ID", value: "" },
      '# "1" lets queued commands transmit (beacon, message, switching digi/IGate/TX on).',
      { key: "BOX_TX", value: "" },
      "# The station call remote transmits must use (base call match; blank = IGATE_CALL, then DIGI_CALL).",
      { key: "BOX_CALL", value: "" },
      "# Digipeater path for remote beacons and messages (blank = no path).",
      { key: "BOX_TX_PATH", value: "WIDE1-1,WIDE2-1" },
      "# Refuse transmit commands queued longer ago than this many seconds.",
      { key: "BOX_CMD_MAX_AGE", value: "900" },
      "# Remote-transmit pacing: transmits at once, then one more every N seconds (ceiling: 10 at once, 6 s)",
      { key: "BOX_TX_BURST", value: "3" },
      { key: "BOX_TX_REFILL_SEC", value: "60" },
      "",
      "# --- gateway position storage: set these on the GATEWAY (deploy/.env, or [vars] in workers/gateway/wrangler.toml",
      '# on the Cloudflare split), not on this box; see docs/reference/cloudflare-costs.md "Cost on D1" ---',
      "# A fix is stored once its station has moved POS_MIN_MOVE_M metres or POS_MIN_INTERVAL_S seconds have passed",
      "# since its last stored fix. Accounts' calls, registered stations, open finds, living caches and every fix",
      "# heard directly on RF are always stored; every fix still reaches the live map. 0 in either stores every fix.",
      { key: "POS_MIN_MOVE_M", value: "25", off: true },
      { key: "POS_MIN_INTERVAL_S", value: "600", off: true },
      "# Daily D1 write budget (rows a day, from 00:00 UTC; on the Worker 1500000 unless set, 90000 on Workers Free;",
      "# on Node/Bun off unless set; 0 = off): near it the gateway stops storing low-value writes and alerts the sysop.",
      '# See docs/reference/cloudflare-costs.md "Write budget".',
      { key: "D1_DAILY_WRITE_BUDGET", value: "1500000", off: true },
      "",
      "# --- gateway embeddable map widget (/embed): set these on the GATEWAY too, not on this box ---",
      '# A MapLibre style URL, or "offline" for the self-contained grid that loads nothing from outside the',
      "# instance (HAMNET, off-grid). Unset: OpenFreeMap liberty, the web app's default basemap.",
      { key: "BASEMAP_STYLE", value: "offline", off: true },
      "# Extra origins the style loads tiles, glyphs or sprites from, when they are not on the style's own host.",
      { key: "BASEMAP_HOSTS", value: "", off: true },
      "",
      "# --- optional: ingest tuning ---",
      "# max packets buffered (drop-oldest) while the gateway is unreachable",
      { key: "INGEST_SPOOL_MAX", value: "5000" },
      "",
      "# --- optional: connected-mode digipeater (needs DIGI_CALL + a KISS TNC) ---",
      '# "1" to also repeat SABM/I/… frames (NET/ROM + FBB relay through us)',
      { key: "DIGI_CONNECTED", value: "" },
      "# viscous-delay ms before repeating (lets a better-placed digi win); blank = off",
      { key: "DIGI_VISCOUS_MS", value: "" },
      "",
      "# --- optional: NET/ROM node (needs a KISS TNC) ---",
      "# our node's callsign-SSID, e.g. OE8XXX-7 — set with NETROM_ALIAS to enable",
      { key: "NETROM_CALL", value: "" },
      "# node alias, e.g. GRAZ",
      { key: "NETROM_ALIAS", value: "" },
      "# NODES broadcast interval ms (blank = spec default ~300000)",
      { key: "NETROM_BROADCAST_MS", value: "" },
      "# link quality assumed for a directly-heard neighbour (blank = 192)",
      { key: "NETROM_PATH_QUALITY", value: "" },
      '# "1" also speaks INP3 (triggered RIFs + RTT metric) alongside NODES',
      { key: "NETROM_INP3", value: "" },
      "# node command surface: netrom (default) | flexnet | tnn | baycom",
      { key: "NODE_PERSONALITY", value: "" },
      "",
      "# --- optional: connected-mode BBS answering inbound connects (needs a KISS TNC) ---",
      "# our BBS callsign-SSID, e.g. OE8XXX-1 — set to enable",
      { key: "BBS_NODE_CALL", value: "" },
      "",
      "# --- optional: FBB mail forwarding to partner BBSes (needs a KISS TNC) ---",
      '# "1" to enable the forwarding scheduler',
      { key: "BBS_FORWARD", value: "" },
      "# our station call used for the forwarding session",
      { key: "BBS_FORWARD_CALL", value: "" },
      "# our advertised SID (blank = a sensible default)",
      { key: "BBS_FORWARD_SID", value: "" },
      "# how often to check partners for due forwards",
      { key: "BBS_FORWARD_POLL_MS", value: "60000" },
      '# "1" offers LZHUF-B1 compressed forwarding (falls back to ASCII per partner)',
      { key: "BBS_FORWARD_COMPRESS", value: "" },
      "# Session pacing: forwarding sessions at once, then one more every N seconds (ceiling: 10 at once, 60 s);",
      "# a partner over the limit waits for the next poll",
      { key: "BBS_FORWARD_BURST", value: "4" },
      { key: "BBS_FORWARD_REFILL_SEC", value: "300" },
      "",
      "# --- optional: AGWPE TNC (Direwolf/SoundModem/UZ7HO over TCP) ---",
      "# set to enable",
      { key: "AGWPE_HOST", value: "" },
      { key: "AGWPE_PORT", value: "8000" },
      "# AGWPE radio-port index (0 = first)",
      { key: "AGWPE_RADIO_PORT", value: "0" },
      "",
      "# --- optional: WA8DED host-mode TNC (TF firmware / TFPCX over TCP) ---",
      "# set to enable",
      { key: "HOSTMODE_HOST", value: "" },
      { key: "HOSTMODE_PORT", value: "3694" },
      "# station call the host-mode TNC uses",
      { key: "HOSTMODE_MYCALL", value: "" },
      "# host-mode radio-port index (0 = first)",
      { key: "HOSTMODE_RADIO_PORT", value: "0" },
      "",
      "# --- optional: AXUDP tunnel (tunnelled AX.25 over UDP — always Tier C, never first-party RF) ---",
      "# set the listen port to enable (default 10093 if enabled without a value)",
      { key: "AXUDP_PORT", value: "" },
      "# bind address (blank = all interfaces)",
      { key: "AXUDP_BIND", value: "" },
      "# host:port,host:port — with peers it's a bidirectional KISS-equivalent port",
      { key: "AXUDP_PEERS", value: "" },
      "",
      "# --- optional: AXIP tunnel (AX.25 over IP; reserved seam) ---",
      '# "1" to enable',
      { key: "AXIP_ENABLE", value: "" },
      { key: "AXIP_BIND", value: "" },
      { key: "AXIP_PEERS", value: "" },
      "",
      "# --- optional: CWOP relay (feeds NOAA; falls back to standard APRS-IS when unset) ---",
      { key: "CWOP_HOST", value: "" },
      { key: "CWOP_PORT", value: "14580" },
    ],
  },
  {
    path: "deploy/.env.example",
    lines: [
      "# Written by ./setup.sh — run it first; it fills everything a working instance needs and keeps what is set.",
      "",
      "# ---- Public site ----",
      "# What Caddy serves: a hostname ⇒ automatic Let's Encrypt TLS; :80 ⇒ plain http (LAN/off-grid, or behind a",
      "# Cloudflare Tunnel, where TLS ends at Cloudflare's edge).",
      { key: "DOMAIN", value: ":80" },
      "# The public origin people open (https://your.host, or http://<LAN address> off-grid). INSTANCE (the",
      "# federation id) and RP_ID (the passkey domain) default to its host; set them only to differ.",
      { key: "APP_URL", value: "https://aprs.example.net", off: true },
      { key: "INSTANCE", value: "aprs.example.net", off: true },
      { key: "RP_ID", value: "example.net", off: true },
      '# Basemap of the embeddable map widget (/embed): a MapLibre style URL, or "offline" for the self-contained',
      "# grid that loads nothing from outside the instance (HAMNET, off-grid). Unset: OpenFreeMap liberty. Extra",
      "# origins the style loads tiles, glyphs or sprites from go in BASEMAP_HOSTS (comma-separated).",
      { key: "BASEMAP_STYLE", value: "offline", off: true },
      { key: "BASEMAP_HOSTS", value: "", off: true },
      "",
      "# ---- APRS-IS feed ----",
      { key: "APRSIS_HOST", value: "rotate.aprs2.net" },
      { key: "APRSIS_PORT", value: "14580" },
      "# your callsign",
      { key: "APRSIS_CALLSIGN", value: "N0CALL" },
      "# your APRS-IS passcode",
      { key: "APRSIS_PASSCODE", value: "00000", placeholder: true },
      "# example: 300 km around Graz; tune to your area",
      { key: "APRSIS_FILTER", value: "r/47.07/15.42/300" },
      { key: "BATCH_MS", value: "2000" },
      "",
      "# ---- Gateway link ----",
      "# Self-host (this compose stack): http://gateway:8080/ingest   (compose default)",
      "# A remote gateway (the Cloudflare split): https://gateway.<you>.workers.dev/ingest",
      { key: "INGEST_URL", value: "http://gateway:8080/ingest" },
      "# REQUIRED — setup.sh generates one (openssl rand -hex 24). Per-operator peer keys for shared gateways.",
      "# It authorises only the ingest plane (packets, outbox, BBS delivery, node mirror, box polling) — never",
      "# operator configuration and never a sign-in session.",
      { key: "INGEST_SECRET", value: "" },
      "",
      "# ---- Operator & session secrets (gateway only — never give these to an ingest box) ----",
      "# OPERATOR_SECRET authorises the operator's scripts (tools/admin/verify-call.mjs, peer trust, forwarding",
      "# partners/rules, donation confirms) via the x-operator-secret header. Leave it empty to close those",
      "# machine paths; a signed-in, verified sysop still administers the instance from the web.",
      "# setup.sh generates one (openssl rand -hex 24); it must differ from INGEST_SECRET.",
      { key: "OPERATOR_SECRET", value: "" },
      "# SESSION_SECRET signs user sessions. Leave it empty and the gateway generates one on first start and",
      "# keeps it beside the database (session.secret in the data volume); set it to pin a value of your own.",
      "# Changing or deleting it signs every user out.",
      { key: "SESSION_SECRET", value: "" },
      "",
      "# ---- Trust / verification ----",
      "# Tier A (RF-corroborated) is DEFAULT-DENY: a find reaches Tier A only from a frame heard directly by a",
      "# receiving site you operate and attest, delivered by that site's own ingest box (its TNC or MeshCom port,",
      "# RF_SITE_CALL / MESHCOM_NODE). List those callsigns here (comma/space separated). An APRS-IS line naming",
      "# a listed site (`qAR,<site>`) never counts — APRS-IS passcodes are public, so anyone can inject one.",
      "# Leave it EMPTY and NO find reaches Tier A locally. Peer corroboration over federation can still grant",
      "# Tier A independently.",
      { key: "FIRST_PARTY_SITES", value: "OE8XXX,OE8YYY", off: true },
      "",
      '# ---- Position storage (gateway only; see docs/reference/cloudflare-costs.md "Cost on D1") ----',
      "# A fix is stored once its station has moved POS_MIN_MOVE_M metres or POS_MIN_INTERVAL_S seconds have passed",
      "# since its last stored fix. Accounts' calls, registered stations, open finds, living caches and every fix",
      "# heard directly on RF are always stored; every fix still reaches the live map. 0 in either stores every fix.",
      { key: "POS_MIN_MOVE_M", value: "25", off: true },
      { key: "POS_MIN_INTERVAL_S", value: "600", off: true },
      "# Daily D1 write budget (rows a day, from 00:00 UTC): near it the gateway stops storing low-value writes (the",
      "# raw packet log first, then unprotected stations' fixes) and alerts the sysop; protected data is always stored.",
      "# It guards the Cloudflare D1 bill; a self-hosted SQLite file costs the same whatever it writes, so it is off",
      '# here unless set. See docs/reference/cloudflare-costs.md "Write budget". 0 = off.',
      { key: "D1_DAILY_WRITE_BUDGET", value: "1500000", off: true },
      "",
      "# ---- Instance operator (see docs/run/first-hour.md) ----",
      "# Your callsign: it administers this instance once you confirm it with tools/admin/verify-call.mjs.",
      { key: "ADMIN_CALLSIGNS", value: "OE8APR", off: true },
      "# Imprint and privacy contact — a public instance must set all three (/imprint, /privacy).",
      { key: "OPERATOR_NAME", value: "", off: true },
      { key: "OPERATOR_ADDRESS", value: "", off: true },
      { key: "OPERATOR_EMAIL", value: "", off: true },
      "",
      "# ---- Federation signing key (gateway only) ----",
      "# Signs this instance's feeds so peers can mirror them. setup.sh generates it with",
      "# node tools/fedkey/genkey.mjs --raw; never commit it.",
      { key: "FED_PRIVATE_KEY", value: "", off: true },
      "",
      '# ---- Federation posture (gateway only; see docs/run/federation/index.md "Running federation safely") ----',
      "# Only you promote a peer to trusted, and no single peer can lift a find to Tier A.",
      { key: "FED_AUTO_PROMOTE", value: "0" },
      { key: "FED_CORROBORATION_QUORUM", value: "2" },
      "# Peers you know, as https URLs; they start trusted. Onboard 44Net peers from Instance admin instead.",
      { key: "FED_PEERS", value: "https://peer.example.org", off: true },
      "# Discovery off: learned peers would arrive disabled, still for you to vet.",
      { key: "FED_DISCOVER", value: "0" },
      "# A hub (FED_SUBMIT_SECRET set) lists the spoke instance ids allowed to submit to it.",
      { key: "FED_SUBMIT_INSTANCES", value: "spoke.example.org", off: true },
      "# A registry (FED_REGISTRY or FED_REGISTRY_DNS) is refused without its pinned authority key.",
      { key: "FED_REGISTRY_KEY", value: "", off: true },
      "",
      "# ---- Email (gateway only; optional) ----",
      "# Sign-in links and the watch-alert digest go out through a Resend-compatible API. Without both values the",
      "# instance sends no mail: members sign in with passkeys (https APP_URL) or, off-grid, with a one-time link",
      "# the operator mints (tools/admin/signin-link.mjs <CALL>). Never set ALLOW_DEV_TOKENS on a real instance —",
      "# it hands sign-in tokens to whoever asks.",
      "# sender address, e.g. aprscaching <noreply@aprs.example.net>",
      { key: "EMAIL_FROM", value: "", off: true },
      "# the provider's API key",
      { key: "EMAIL_API_KEY", value: "", off: true },
      "",
      "# ---- Radio transports (optional; see docs/run/radios/rf-ingest.md) ----",
      { key: "KISS_TNC_HOST", value: "192.168.1.20", off: true },
      { key: "KISS_TNC_PORT", value: "8001", off: true },
      "# Names this box as the receiving site of what its own TNC hears directly; list it in FIRST_PARTY_SITES",
      "# for Tier A. Leave it unset when the TNC host is someone else's station (a club digi, a remote node).",
      { key: "RF_SITE_CALL", value: "OE8APR-10", off: true },
      { key: "MESHCOM_NODE", value: "192.168.1.50=OE8APR-12", off: true },
      "# Inside Docker the listener binds the container's own interface; also publish 1799/udp on the ingest service.",
      { key: "MESHCOM_BIND", value: "0.0.0.0", off: true },
      "",
      "# ---- Cloudflare Tunnel ingress (self-host without open ports; compose.home.yml) ----",
      { key: "TUNNEL_TOKEN", value: "" },
      "",
      "# ---- Cloudflare in front of a self-host box (tunnel or proxied DNS) ----",
      "# Keep Cloudflare's cf-connecting-ip as the client address for per-IP rate limits. Set it only when the",
      "# origin is reachable solely through Cloudflare (firewall 80/443 to Cloudflare's ranges); a client that",
      "# reaches the origin directly could otherwise choose its own address. compose.home.yml sets it for the tunnel.",
      { key: "TRUST_CF", value: "1", off: true },
      "",
      "# ---- Backups ----",
      "# deploy/backup.sh snapshots the SQLite DB nightly and UPLOADS it — it fails loudly if no destination",
      '# is set (a /tmp-only "backup" is not a backup). Configure exactly one destination:',
      "# local/mounted dir (not the DB's disk)",
      { key: "BACKUP_DIR", value: "/mnt/backups", off: true },
      "# OCI Object Storage (needs the oci CLI)",
      { key: "OCI_BUCKET", value: "aprscaching-backups", off: true },
      "# S3/R2 bucket (needs the aws CLI) …",
      { key: "BACKUP_BUCKET", value: "aprscaching-backups", off: true },
      "#   … paired with an S3-compatible endpoint",
      { key: "R2_ENDPOINT", value: "https://<acct>.r2.cloudflarestorage.com", off: true },
      "# BACKUP_DIR snapshots older than this are deleted. Bucket destinations are append-only: expire them",
      "# with a lifecycle rule on the bucket's db/ prefix, or set BACKUP_PRUNE_BUCKET=1 to have the script",
      "# delete them (the bucket key then needs delete permission).",
      { key: "BACKUP_RETENTION_DAYS", value: "30", off: true },
      { key: "BACKUP_PRUNE_BUCKET", value: "0", off: true },
      "",
      "# ---- AGPL §13 source link ----",
      "# The instance auto-stamps its commit from git when run from a clone. If you MODIFY the code, set",
      "# SOURCE_REPO to YOUR published fork (and SOURCE_COMMIT if not deploying from git).",
      { key: "SOURCE_REPO", value: "https://github.com/<you>/aprscaching", off: true },
      { key: "SOURCE_COMMIT", value: "", off: true },
    ],
  },
];
