// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * docs-theme.mjs — derives the MkDocs manual's theme from the web app's design tokens, so the published manual
 * and the app share one palette, type and shape.
 *
 * Reads apps/web/src/styles/tokens.css and fonts.css and writes docs/stylesheets/tokens.gen.css:
 *   - the app's [data-theme] token sets become Material's colour schemes (dark → slate, light → default); the
 *     Phosphor set and its face are dropped, since the manual has no Phosphor scheme;
 *   - the cascade layer wrapper is dropped (Material's CSS is unlayered, and a layered rule would lose to it);
 *   - the root token set also applies to [data-md-color-scheme], so the tokens built from other tokens
 *     (color-mix of the brand, say) are worked out again for the scheme Material puts on the body;
 *   - absolute /fonts/ URLs become relative to the stylesheet.
 * It copies the fonts and brand images the manual uses into docs/assets/, and Mermaid's browser build from the
 * web app's locked dependency into docs/assets/vendor/ (not committed: the docs workflow runs this first).
 *
 * If tokens.css changes shape (a theme selector or the layer wrapper this relies on goes missing), it fails
 * rather than writing a theme with a scheme silently missing.
 *
 *   node tools/dev/docs-theme.mjs          write the generated files
 *   node tools/dev/docs-theme.mjs --check  exit 1 if the committed ones are out of date (CI)
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "../..");
const web = join(root, "apps/web");
const out = join(root, "docs/stylesheets/tokens.gen.css");

function fail(msg) {
  console.error(`docs-theme: ${msg}`);
  process.exit(1);
}

const strip = (css) => css.replace(/\/\*[\s\S]*?\*\//g, "");

/** Remove the rule starting at the first match of SELECTOR, braces balanced; fail if it is not there. */
function dropRule(css, selector) {
  const at = css.indexOf(selector);
  if (at < 0) fail(`tokens.css has no ${selector} block`);
  let depth = 0;
  for (let i = css.indexOf("{", at); i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}" && --depth === 0) return css.slice(0, at) + css.slice(i + 1);
  }
  return fail(`unbalanced braces after ${selector}`);
}

/** `@layer tokens { … }` → its body. */
function unlayer(css) {
  const m = /@layer\s+tokens\s*\{/.exec(css);
  if (!m) fail("tokens.css is no longer wrapped in @layer tokens");
  const end = css.lastIndexOf("}");
  return css.slice(0, m.index) + css.slice(m.index + m[0].length, end) + css.slice(end + 1);
}

function rescope(css) {
  for (const t of ["light", "dark"])
    if (!css.includes(`:root[data-theme="${t}"]`)) fail(`tokens.css has no ${t} theme`);
  const done = css
    .replace(/:root\[data-theme="light"\]/g, '[data-md-color-scheme="default"]')
    .replace(/:root\[data-theme="dark"\]/g, '[data-md-color-scheme="slate"]')
    .replace(/(^|[\s,}]):root(\s*\{)/g, "$1:root,\n[data-md-color-scheme]$2");
  if (done.includes("data-theme")) fail("tokens.css has a [data-theme] selector this script does not map");
  return done;
}

const tokensSrc = strip(readFileSync(join(web, "src/styles/tokens.css"), "utf8"));
const tokens = rescope(dropRule(unlayer(tokensSrc), ':root[data-theme="phosphor"]'));

const fontsSrc = strip(readFileSync(join(web, "src/styles/fonts.css"), "utf8"));
const phosphorFace = /@font-face\s*\{[^}]*PxPlus IBM VGA8[^}]*\}/;
if (!phosphorFace.test(fontsSrc)) fail("fonts.css has no PxPlus IBM VGA8 face to leave out");
const fontFaces = fontsSrc.replace(phosphorFace, "").replace(/url\("\/fonts\//g, 'url("../assets/fonts/');

const tidy = (css) =>
  css
    .split("\n")
    .map((l) => l.replace(/\s+$/, ""))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
const gen =
  "/* GENERATED by tools/dev/docs-theme.mjs from apps/web/src/styles/{tokens,fonts}.css — do not edit. */\n" +
  tidy(fontFaces) +
  "\n\n" +
  tidy(tokens) +
  "\n";

const committed = [
  ...[
    "Fredoka-500.woff2",
    "Fredoka-600.woff2",
    "Fredoka-700.woff2",
    "IBMPlexMono-400.woff2",
    "IBMPlexMono-500.woff2",
    "IBMPlexMono-600.woff2",
    "OFL-Fredoka.txt",
    "OFL-IBMPlexMono.txt",
  ].map((f) => [join(web, "public/fonts", f), `assets/fonts/${f}`]),
  [join(web, "public/brand/beacon-green.png"), "assets/brand/beacon-green.png"],
  [join(web, "public/icons/favicon-32x32.png"), "assets/brand/favicon.png"],
];

const same = (a, b) => existsSync(b) && readFileSync(a).equals(readFileSync(b));

if (process.argv.includes("--check")) {
  const stale = existsSync(out) && readFileSync(out, "utf8") === gen ? [] : ["docs/stylesheets/tokens.gen.css"];
  for (const [from, to] of committed) if (!same(from, join(root, "docs", to))) stale.push(`docs/${to}`);
  if (stale.length) fail(`out of date (run: node tools/dev/docs-theme.mjs):\n  ${stale.join("\n  ")}`);
  console.log("✓ docs theme matches the app's tokens");
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, gen);
  const require = createRequire(join(web, "package.json"));
  const mermaid = dirname(require.resolve("mermaid/package.json"));
  const vendor = [
    [join(mermaid, "dist/mermaid.min.js"), "assets/vendor/mermaid.min.js"],
    [join(mermaid, "LICENSE"), "assets/vendor/mermaid.LICENSE.txt"],
  ];
  for (const [from, to] of [...committed, ...vendor]) {
    const dest = join(root, "docs", to);
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(from, dest);
  }
  const { version } = JSON.parse(readFileSync(join(mermaid, "package.json"), "utf8"));
  console.log(
    `wrote docs/stylesheets/tokens.gen.css, docs/assets/{fonts,brand}, and Mermaid ${version} to docs/assets/vendor`,
  );
}
