// SPDX-License-Identifier: MIT
/**
 * Every configuration key, grouped by the unit that owns it: the gateway (in the order of the settings it
 * forwards), the ingest box, then the server process, the licence importer, the desktop launcher, the web
 * build, the deploy scripts and the Pocket extras. The fields are described on ConfigKey in config.ts; the
 * one-line hints and the documentation tables are in configdocs.ts.
 */
import type { ConfigKey } from "./config.js";

export const CONFIG_KEYS = {
  INGEST_SECRET: {
    type: "string",
    units: ["gateway", "server", "desktop", "ingest", "pocket"],
    secret: true,
    publicRequired: true,
  },
  OPERATOR_SECRET: { type: "string", units: ["gateway", "server", "desktop", "pocket", "licence"], secret: true },
  SESSION_SECRET: { type: "string", units: ["gateway", "server", "desktop"], secret: true, publicRequired: true },
  SESSION_TTL_DAYS: { type: "int", units: ["gateway"], default: "30" },
  SESSION_EPOCH: { type: "int", units: ["gateway"], default: "0" },
  TRUST_PROXY: {
    type: "enum",
    units: ["gateway", "server"],
    values: ["0", "1"],
    shapes: ["selfhost", "baremetal", "pocket", "desktop"],
  },
  TRUST_CF: {
    type: "enum",
    units: ["gateway", "server"],
    values: ["0", "1"],
    shapes: ["selfhost", "baremetal", "pocket", "desktop"],
  },
  ADMIN_CALLSIGNS: { type: "list", units: ["gateway", "pocket"], publicRequired: true },
  INSTANCE: { type: "string", units: ["gateway", "pocket"] },
  FED_PRIVATE_KEY: { type: "string", units: ["gateway", "pocket"], secret: true },
  FED_KEY_HISTORY: { type: "json", units: ["gateway"] },
  FED_ROTATIONS: { type: "json", units: ["gateway"] },
  FED_ROTATION_GRACE_DAYS: { type: "number", units: ["gateway"], default: "7" },
  FED_REGISTRY: { type: "json", units: ["gateway"] },
  FED_REGISTRY_KEY: { type: "string", units: ["gateway"] },
  FED_REGISTRY_DNS: { type: "string", units: ["gateway"] },
  FED_OPERATOR: { type: "string", units: ["gateway"] },
  FED_APRS_CALL: { type: "string", units: ["gateway"] },
  FIRST_PARTY_SITES: { type: "list", units: ["gateway"] },
  FED_PEERS: { type: "list", units: ["gateway", "pocket"] },
  FED_DISCOVER: { type: "string", units: ["gateway"] },
  FED_CORROBORATION_QUORUM: { type: "int", units: ["gateway"], default: "2" },
  FED_AUTO_PROMOTE: { type: "int", units: ["gateway"], default: "0" },
  FED_CORROBORATION_SECRET: { type: "string", units: ["gateway"], secret: true },
  FED_CORROBORATION_REQUIRE_KNOWN: { type: "enum", units: ["gateway"], values: ["0", "1"] },
  FED_REVEAL_IGATE: { type: "string", units: ["gateway"] },
  FED_SYNC_REGION: { type: "string", units: ["gateway", "pocket"] },
  FED_ENDPOINTS: { type: "json", units: ["gateway", "pocket"] },
  FED_ALLOW_PRIVATE: {
    type: "enum",
    units: ["gateway", "server"],
    values: ["0", "1"],
    shapes: ["selfhost", "baremetal", "pocket", "desktop"],
  },
  FED_SUBMIT_SECRET: { type: "string", units: ["gateway", "pocket"], secret: true },
  FED_SUBMIT_INSTANCES: { type: "list", units: ["gateway"] },
  FED_HUB_URL: { type: "string", units: ["gateway", "pocket"] },
  FED_RELAY_SECRET: { type: "string", units: ["gateway"], secret: true },
  RETENTION: { type: "json", units: ["gateway", "pocket"] },
  MESHCOM_META_MIN_S: { type: "int", units: ["gateway"], default: "300" },
  MESHCOM_NODE_TTL_DAYS: { type: "int", units: ["gateway"], default: "7" },
  MESHCOM_LINK_TTL_HOURS: { type: "int", units: ["gateway"], default: "48" },
  POS_MIN_MOVE_M: { type: "number", units: ["gateway"], default: "25" },
  POS_MIN_INTERVAL_S: { type: "number", units: ["gateway"], default: "600" },
  D1_DAILY_WRITE_BUDGET: { type: "int", units: ["gateway"] },
  DOH_URL: { type: "string", units: ["gateway", "pocket"], default: "https://cloudflare-dns.com/dns-query" },
  AMPR_DNS_RESOLVERS: {
    type: "list",
    units: ["gateway"],
    default: "https://cloudflare-dns.com/dns-query,https://dns.google/resolve,https://dns.quad9.net:5053/dns-query",
  },
  AMPR_REQUIRE_DNSSEC: { type: "enum", units: ["gateway"], values: ["0", "1", "false", "true"] },
  LOTW_CA_PEM: { type: "string", units: ["gateway"] },
  OKAPI_BASE: { type: "string", units: ["gateway"] },
  OKAPI_KEY: { type: "string", units: ["gateway"], secret: true },
  BBS_CALL: { type: "string", units: ["gateway"], default: "APRSCG" },
  RADIO_REPLIES: { type: "enum", units: ["gateway"], values: ["0", "1"] },
  API_RATE_WINDOW_SEC: { type: "int", units: ["gateway"], default: "60" },
  API_RATE_ANON: { type: "int", units: ["gateway"], default: "60" },
  API_RATE_KEYED: { type: "int", units: ["gateway"], default: "600" },
  SPOTS_ENABLED: { type: "enum", units: ["gateway"], values: ["0", "1", "false", "no", "true", "yes"] },
  SPOTS_SOURCES: { type: "list", units: ["gateway"] },
  SPOTS_TTL_SEC: { type: "int", units: ["gateway"], default: "120" },
  SPOTS_USER_AGENT: {
    type: "string",
    units: ["gateway"],
    default: "APRScaching (+https://github.com/apachler/aprscaching)",
  },
  SPOTS_RECEPTION_URLS: { type: "json", units: ["gateway"] },
  BASEMAP_STYLE: { type: "string", units: ["gateway"], default: "https://tiles.openfreemap.org/styles/liberty" },
  BASEMAP_HOSTS: { type: "list", units: ["gateway"] },
  APP_URL: { type: "url", units: ["gateway", "pocket"], publicRequired: true },
  CORS_ORIGINS: { type: "list", units: ["gateway"] },
  RP_ID: { type: "string", units: ["gateway"] },
  EMAIL_FROM: { type: "string", units: ["gateway"] },
  EMAIL_API_KEY: { type: "string", units: ["gateway"], secret: true },
  ALLOW_DEV_TOKENS: { type: "enum", units: ["gateway"], values: ["0", "1", "false", "true"] },
  OPERATOR_LINKS_FOR_ANY_CALL: { type: "enum", units: ["gateway", "pocket"], values: ["0", "1"] },
  VAPID_PUBLIC: { type: "string", units: ["gateway"] },
  VAPID_PRIVATE: { type: "string", units: ["gateway"], secret: true },
  VAPID_SUBJECT: { type: "string", units: ["gateway"], default: "mailto:admin@aprscaching.net" },
  SUPPORT_LINKS: { type: "json", units: ["gateway"] },
  SOURCE_REPO: { type: "string", units: ["gateway"], default: "https://github.com/apachler/aprscaching" },
  OPERATOR_NAME: { type: "string", units: ["gateway"], publicRequired: true },
  OPERATOR_ADDRESS: { type: "string", units: ["gateway"], publicRequired: true },
  OPERATOR_EMAIL: { type: "string", units: ["gateway"], publicRequired: true },
  SOURCE_COMMIT: { type: "string", units: ["gateway", "server"] },
  SOURCE_TAG: { type: "string", units: ["gateway"] },
  SOURCE_BUILT_AT: { type: "int", units: ["gateway"] },
  INGEST_URL: { type: "url", units: ["ingest"], default: "http://127.0.0.1:8787/ingest" },
  BATCH_MS: { type: "int", units: ["ingest"], default: "1500" },
  INGEST_SPOOL_MAX: { type: "int", units: ["ingest"], default: "5000" },
  APRSIS_HOST: { type: "string", units: ["ingest", "pocket"], default: "rotate.aprs2.net" },
  APRSIS_PORT: { type: "int", units: ["ingest", "pocket"], default: "14580" },
  APRSIS_CALLSIGN: { type: "string", units: ["ingest", "pocket"], default: "N0CALL" },
  APRSIS_PASSCODE: { type: "int", units: ["ingest"], default: "-1", secret: true },
  APRSIS_FILTER: { type: "string", units: ["ingest", "pocket"], default: "r/47.07/15.42/300" },
  KISS_TNC_HOST: { type: "string", units: ["ingest", "pocket"] },
  KISS_TNC_PORT: { type: "int", units: ["ingest", "pocket"], default: "8001" },
  AGWPE_HOST: { type: "string", units: ["ingest"] },
  AGWPE_PORT: { type: "int", units: ["ingest"], default: "8000" },
  AGWPE_RADIO_PORT: { type: "int", units: ["ingest"], default: "0" },
  HOSTMODE_HOST: { type: "string", units: ["ingest"] },
  HOSTMODE_PORT: { type: "int", units: ["ingest"], default: "3694" },
  HOSTMODE_MYCALL: { type: "string", units: ["ingest"] },
  HOSTMODE_RADIO_PORT: { type: "int", units: ["ingest"], default: "0" },
  MESHTASTIC_HOST: { type: "string", units: ["ingest"] },
  MESHTASTIC_PORT: { type: "int", units: ["ingest"], default: "4403" },
  MESHTASTIC_MQTT_URL: { type: "url", units: ["ingest"], secret: true },
  MESHTASTIC_MQTT_TOPIC: { type: "string", units: ["ingest"], default: "msh/#" },
  MESHCOM_NODE: { type: "list", units: ["ingest", "pocket"] },
  MESHCOM_PORT: { type: "int", units: ["ingest", "pocket"], default: "1799" },
  MESHCOM_BIND: { type: "string", units: ["ingest"] },
  MESHCOM_FANOUT: { type: "list", units: ["ingest"] },
  MESHCOM_RATE: { type: "number", units: ["ingest"], default: "20" },
  MESHCOM_STALE_MIN: { type: "number", units: ["ingest"], default: "30" },
  MESHCOM_TX: { type: "enum", units: ["ingest"], values: ["0", "1", "false"] },
  MESHCOM_TX_CALL: { type: "string", units: ["ingest"] },
  MESHCOM_TX_AUDIT: { type: "string", units: ["ingest"] },
  MESHCOM_TX_BURST: { type: "int", units: ["ingest"], default: "3" },
  MESHCOM_TX_REFILL_SEC: { type: "number", units: ["ingest"], default: "60" },
  AXUDP_PORT: { type: "int", units: ["ingest"] },
  AXUDP_BIND: { type: "string", units: ["ingest"] },
  AXUDP_PEERS: { type: "list", units: ["ingest"] },
  AXIP_ENABLE: { type: "string", units: ["ingest"] },
  AXIP_PEERS: { type: "list", units: ["ingest"] },
  AXIP_BIND: { type: "string", units: ["ingest"] },
  DIGI_CALL: { type: "string", units: ["ingest"] },
  DIGI_ALIASES: { type: "list", units: ["ingest"], default: "WIDE1,WIDE2" },
  DIGI_CONNECTED: { type: "enum", units: ["ingest"], values: ["0", "1", "false"] },
  DIGI_VISCOUS_MS: { type: "int", units: ["ingest"] },
  NETROM_CALL: { type: "string", units: ["ingest"] },
  NETROM_ALIAS: { type: "string", units: ["ingest"] },
  NETROM_BROADCAST_MS: { type: "int", units: ["ingest"], default: "300000" },
  NETROM_PATH_QUALITY: { type: "int", units: ["ingest"], default: "192" },
  NETROM_INP3: { type: "enum", units: ["ingest"], values: ["0", "1", "false"] },
  NODE_PERSONALITY: { type: "string", units: ["ingest"], default: "netrom" },
  BBS_NODE_CALL: { type: "string", units: ["ingest"] },
  BBS_FORWARD: { type: "enum", units: ["ingest"], values: ["0", "1", "false"] },
  BBS_FORWARD_CALL: { type: "string", units: ["ingest"] },
  BBS_FORWARD_POLL_MS: { type: "int", units: ["ingest"], default: "60000" },
  BBS_FORWARD_SID: { type: "string", units: ["ingest"] },
  BBS_FORWARD_COMPRESS: { type: "enum", units: ["ingest"], values: ["0", "1", "false"] },
  BBS_FORWARD_BURST: { type: "int", units: ["ingest"], default: "4" },
  BBS_FORWARD_REFILL_SEC: { type: "number", units: ["ingest"], default: "300" },
  IGATE_CALL: { type: "string", units: ["ingest"] },
  IGATE_PASS: { type: "string", units: ["ingest"], secret: true },
  IGATE_FILTER: { type: "string", units: ["ingest"] },
  IGATE_LOCAL_TTL: { type: "int", units: ["ingest"], default: "1800" },
  IGATE_TX_PATH: { type: "list", units: ["ingest"] },
  IGATE_TX_BURST: { type: "int", units: ["ingest"], default: "6" },
  IGATE_TX_REFILL_SEC: { type: "number", units: ["ingest"], default: "10" },
  RF_SITE_CALL: { type: "string", units: ["ingest", "pocket"] },
  BOX_ID: { type: "string", units: ["ingest"] },
  BOX_TX: { type: "enum", units: ["ingest"], values: ["0", "1", "false"] },
  BOX_CALL: { type: "string", units: ["ingest"] },
  BOX_TX_PATH: { type: "list", units: ["ingest"], default: "WIDE1-1,WIDE2-1" },
  BOX_CMD_MAX_AGE: { type: "int", units: ["ingest"], default: "900" },
  BOX_POLL_MS: { type: "int", units: ["ingest"], default: "5000" },
  BOX_SERVICE_CALL: { type: "string", units: ["ingest"], default: "APRSCG" },
  BOX_TX_BURST: { type: "int", units: ["ingest"], default: "3" },
  BOX_TX_REFILL_SEC: { type: "number", units: ["ingest"], default: "60" },
  APRSIS_SERVICE_CALL: { type: "string", units: ["ingest"] },
  APRSIS_SERVICE_PASS: { type: "string", units: ["ingest"], secret: true },
  CWOP_HOST: { type: "string", units: ["ingest"] },
  CWOP_PORT: { type: "int", units: ["ingest"], default: "14580" },
  PORT: { type: "int", units: ["server", "desktop", "pocket"], default: "8787" },
  DB_PATH: { type: "string", units: ["server", "deploy", "pocket"], shapes: ["selfhost", "baremetal", "pocket"] },
  MIGRATIONS_DIR: { type: "string", units: ["server", "desktop"] },
  MEDIA_DIR: { type: "string", units: ["server", "pocket"], shapes: ["selfhost", "baremetal", "pocket"] },
  FED_SYNC_INTERVAL_MS: { type: "int", units: ["server"], default: "300000" },
  WEB_DIST: { type: "string", units: ["server", "desktop"] },
  HTTPS_PORT: { type: "int", units: ["server", "pocket"], shapes: ["selfhost", "baremetal", "pocket"] },
  TLS_CERT: { type: "string", units: ["server", "pocket"], shapes: ["selfhost", "baremetal", "pocket"] },
  TLS_KEY: { type: "string", units: ["server"], shapes: ["selfhost", "baremetal", "pocket"] },
  TLS_CA_CERT: { type: "string", units: ["server"], shapes: ["selfhost", "baremetal", "pocket"] },
  LICENCE_SOURCES: { type: "list", units: ["licence"] },
  BASE: { type: "url", units: ["licence"], default: "http://127.0.0.1:8787" },
  HOST: { type: "string", units: ["desktop"], default: "127.0.0.1" },
  DATA_DIR: { type: "string", units: ["desktop"] },
  VITE_API_BASE: { type: "string", units: ["web"] },
  VITE_BASEMAP: { type: "string", units: ["web"] },
  VITE_BASEMAP_STYLE: { type: "string", units: ["web"] },
  VITE_SAT_TILES: { type: "string", units: ["web"] },
  VITE_SAT_ATTRIBUTION: { type: "string", units: ["web"] },
  VITE_TOOL_REGISTRY: { type: "string", units: ["web"], default: "/tools/registry.json" },
  VITE_TOOL_REGISTRY_AUTHORITY: {
    type: "string",
    units: ["web"],
    default: "J12Zxjkj1-wbUYMgw9wEMfiNB85u4y6tyiQLfQaCink",
  },
  DOMAIN: { type: "string", units: ["deploy"], default: ":80", shapes: ["selfhost"] },
  TUNNEL_TOKEN: { type: "string", units: ["deploy"], secret: true, shapes: ["selfhost"] },
  BACKUP_DIR: { type: "string", units: ["deploy"], shapes: ["selfhost", "baremetal", "desktop"] },
  OCI_BUCKET: { type: "string", units: ["deploy"], shapes: ["selfhost", "baremetal", "desktop"] },
  BACKUP_BUCKET: { type: "string", units: ["deploy"], shapes: ["selfhost", "baremetal", "desktop"] },
  R2_ENDPOINT: { type: "url", units: ["deploy"], shapes: ["selfhost", "baremetal", "desktop"] },
  BACKUP_RETENTION_DAYS: {
    type: "int",
    units: ["deploy"],
    default: "30",
    shapes: ["selfhost", "baremetal", "desktop"],
  },
  BACKUP_PRUNE_BUCKET: {
    type: "enum",
    units: ["deploy"],
    default: "0",
    values: ["0", "1"],
    shapes: ["selfhost", "baremetal", "desktop"],
  },
  CF_API_TOKEN: { type: "string", units: ["deploy"], secret: true, shapes: ["selfhost"] },
  CF_ZONE_ID: { type: "string", units: ["deploy"], shapes: ["selfhost"] },
  POCKET_ALERTS: { type: "enum", units: ["pocket"], default: "0", values: ["0", "1"] },
  POCKET_ALERTS_SPEAK: { type: "enum", units: ["pocket"], default: "0", values: ["0", "1"] },
  POCKET_ALERTS_SPEAK_BODY: { type: "enum", units: ["pocket"], default: "0", values: ["0", "1"] },
  POCKET_BATTERY_LOW: { type: "int", units: ["pocket"], default: "20" },
  POCKET_SYNC_MOBILE: { type: "enum", units: ["pocket"], default: "0", values: ["0", "1"] },
} as const satisfies Record<string, ConfigKey>;
